extend type Query{
  indecisionList(limit: Int = 0, offset: Int = 0): [Indecision]
}

extend type Mutation{
  createIndecision(data: IndecisionInput): Boolean
  removeIndecision(id: Int!): Boolean
  removeAllIndecision(option: String = "all"): Boolean
}

type Indecision {
  id: Int
  title: String
}

input IndecisionInput{
  title: String
}